var i = 0;

var fnames = [["main","main.html","blank.txt"],
	      ["propertiesofminerals","propertiesofminerals.jpg","propertiesofminerals.html"],
	      ["thinsections","propertiesofminerals.jpg","mineralsinthinsection.html"],
	      ["colourinthinsection","colour.jpg","colourinthinsection.html"],
	      ["colourinthinsection2","bippl.html","colourinthinsection2.html"],
	      ["shapeinthinsection","shape.html","shapeinthinsection.html"],
	      ["shapeinthinsection2","shape2.html","shapeinthinsection2.html"],
	      ["cleavageinthinsection","cleavage.jpg","cleavageinthinsection.html"],
	      ["cleavageinthinsection3","cleavage2.jpg","cleavageinthinsection3.html"],
	      ["cleavageinthinsection5","cleavage3.jpg","cleavageinthinsection5.html"],
	      ["reliefinthinsection","relief.jpg","reliefinthinsection.html"],
	      ["reliefinthinsection2","becke.html","reliefinthinsection2.html"],
	      ["birefringenceinthinsection","birefringence.jpg","birefringenceinthinsection.html"],
	      ["birefringenceinthinsection2","birefringence2.jpg","birefringenceinthinsection2.html"],
	      ["birefringenceinthinsection3","birefringence3.jpg","birefringenceinthinsection3.html"],
	      ["birefringenceinthinsection4","birefringence4.jpg","birefringenceinthinsection4.html"],
	      ["twinninginthinsection","twinning.jpg","twinninginthinsection.html"],
	      ["extinctioninthinsection","extinction.html","extinctioninthinsection.html"],
	      ["handspecimens","handspecimens.jpg","mineralsinhandspecimen.html"],
	      ["colourinhandspecimen","handcolour.jpg","colourinhandspecimen.html"],
	      ["transparencyinhandspecimen","handtransparency.jpg","transparencyinhandspecimen.html"],
	      ["transparencyinhandspecimen3","handtransparency2.jpg","transparencyinhandspecimen3.html"],
	      ["habitinhandspecimen","handshape.html","habitinhandspecimen.html"],
	      ["cleavageinhandspecimen","handcleavage.jpg","cleavageinhandspecimen.html"],
	      ["streak","handstreak.jpg","streak.html"],
	      ["hardness","hardness.html","blank.txt"],
	      ["gravity","gravity.html","blank.txt"],
	      ["minerals","minerals.JPG","mineralindex.html"],
	      ["quartz","quartz.JPG","quartz.html"],
	      ["quartz2","quartz2.JPG","quartz2.html"],
	      ["anorthite","anorthite.jpg","anorthite.html"],
	      ["bytownite","bytownite.JPG","bytownite.html"],
	      ["albite","7-plag-xpl.JPG","albite.html"],
	      ["albite2","albite.JPG","albite2.html"],
	      ["microcline","microcline.JPG","microcline.html"],
	      ["microcline2","perthite.JPG","microcline.html"],
	      ["microcline3","microcline2.JPG","microcline2.html"],
	      ["biotiteppl","biotiteppl.JPG","biotiteppl.html"],
	      ["biotitehand","biotitehand.html","biotitehand.html"],
	      ["muscoviteppl","muscoviteppl.JPG","muscoviteppl.html"],
	      ["muscovitehand","muscovitehand.JPG","muscovitehand.html"],
	      ["olivineppl","olivineppl.JPG","olivineppl.html"],
	      ["olivinehand","olivinehand.JPG","olivinehand.html"],
	      ["cpxppl","cpxppl.JPG","cpxppl.html"],
	      ["cpxhand","cpxhand.JPG","cpxhand.html"],
	      ["opxppl","opxppl.JPG","opxppl.html"],
	      ["opxhand","opxhand.JPG","opxhand.html"],
	      ["amphiboleppl","amphibole1ppl.JPG","amphibole.html"],
	      ["amphibole2ppl","amphibole2ppl.JPG","amphiboleppl.html"],
	      ["amphibolehand","amphibolehand.JPG","amphibolehand.html"],
	      ["garnetppl","garnetppl.JPG","garnetppl.html"],
	      ["garnethand","garnethand.JPG","garnethand.html"],
	      ["andalusiteppl","andalusiteppl.JPG","andalusiteppl.html"],
	      ["andalusitehand","andalusitehand.JPG","andalusitehand.html"],
	      ["sillimaniteppl","sillimaniteppl.JPG","sillimaniteppl.html"],
	      ["sillimanitehand","sillimanitehand.JPG","sillimanitehand.html"],
	      ["kyaniteppl","kyaniteppl.JPG","kyaniteppl.html"],
	      ["kyanitehand","kyanitehand.jpg","kyanitehand.html"],
	      ["calciteppl","calciteppl.JPG","calciteppl.html"],
	      ["calcitehand","calcitehand.JPG","calcitehand.html"],
	      ["practicals","granitehand.jpg","practicals.html"],
	      ["igneous","granitehand.jpg","igneous.html"],
	      ["granite","granitehand.jpg","granite.html"],
	      ["granitethinsection","graniteppl.JPG","graniteppl.html"],
	      ["granitegrainsize","graniteppl.JPG","granitegrainsizeppl.html"],
	      ["granitetexture","graniteppl.JPG","granitetextureppl.html"],
	      ["graniteintrusive","graniteppl.JPG","graniteintrusiveppl.html"],
	      ["graniteCI","graniteppl.JPG","graniteCIppl.html"],
	      ["granite4minerals","graniteppl.JPG","granite4mineralsppl.html"],
	      ["graniteminA","7_minA.JPG","graniteminA.html"],
	      ["graniteminAzoom","7_minAzoom.JPG","graniteminAcolour.html"],
	      ["graniteminApleochroism","graniteminApleochroism.html","graniteminApleochroism.html"],
	      ["graniteminAhabit","7_minAzoom.JPG","graniteminAhabit.html"],
	      ["graniteminAcleavage","7_minAzoom.JPG","graniteminAcleavage.html"],
	      ["graniteminArelief","7_minAzoom.JPG","graniteminArelief.html"],
	      ["graniteminAanalyserin","7_minAzoom.JPG","graniteanalyserin.html"],
	      ["graniteminAbirefringence","graniteminAbirefringence.html","graniteminAbirefringence.html"],
	      ["graniteminAtwinning","7-plag-xpl.JPG","graniteminAtwinning.html"],
	      ["graniteminAtwinning2","7-plag-twins.JPG","graniteminAtwinning2.html"],
	      ["graniteminAzoning","graniteminAbirefringence.html","graniteminAzoning.html"],
	      ["graniteminAname","7_minAzoom.JPG","graniteminAname.html"],
	      ["graniteminAproportion","plagproportion.html","graniteminAproportion.html"],
	      ["graniteminAconclusion","plagconclusion.html","blank.txt"],
	      ["granitequartzppl","granitequartzppl.jpg","granitequartzppl1.html"],
	      ["granitequartzpplmovie","granitequartzppl.html","granitequartzppl2.html"],
	      ["granitequartzxpl","granitequartzxpl.jpg","granitequartzxpl1.html"],
	      ["granitequartzxplmovie","granitequartzxpl.html","granitequartzxpl2.html"],
	      ["graniteorthoclaseppl","graniteorthoclaseppl.jpg","graniteorthoclaseppl1.html"],
	      ["graniteorthoclasepplmovie","graniteorthoclaseppl.html","graniteorthoclaseppl2.html"],
	      ["graniteorthoclasexpl","graniteorthoclasexpl.jpg","graniteorthoclasexpl1.html"],
	      ["graniteorthoclasexplmovie","graniteorthoclasexpl.html","graniteorthoclasexpl2.html"],
	      ["graniteobiotiteppl","granitebiotiteppl.jpg","granitebiotiteppl1.html"],
	      ["graniteobiotitexpl","granitebiotitexpl.jpg","granitebiotitexpl1.html"],
	      ["granitedescription","granitedescription.html","blank.txt"],
	      ["granitehand","granitehand.jpg","granitehand.html"],
	      ["granitehand1","granitehand.jpg","granitehand1.html"],
	      ["granitehand2","granitehand.jpg","granitehand2.html"],
	      ["granitehandorthoclase","granitehandorthoclase.jpg","granitehandorthoclase.html"],
	      ["granitehandorthoclase1","granitehandorthoclase.jpg","granitehandorthoclase1.html"],
	      ["granitehandquartz","granitehandquartz.jpg","granitehandquartz.html"],
	      ["granitehandquartz1","granitehandquartz.jpg","granitehandquartz1.html"],
	      ["granitehandplagioclase","granitehandplagioclase.jpg","granitehandplagioclase.html"],
	      ["granitehandplagioclase1","granitehandplagioclase.jpg","granitehandplagioclase1.html"],
	      ["granitehandbiotite","granitehandbiotite.jpg","granitehandbiotite.html"],
	      ["granitehandamphibole","granitehandbiotite.jpg","granitehandamphibole.html"],
	      ["granitehandname","granitehand.jpg","granitename.html"],
	      ["granitehandpetrogenesis","granitehand.jpg","granitepetrogenesis.html"],
	      ["granitehanddescription","granitehanddescription.jpg","granitehanddescription.html"],
	      ["basalt","handbasalt.jpg","basalt.html"],
	      ["basaltthinsection","basaltppl.jpg","basaltppl.html"],
	      ["basaltolivine","basaltolivineppl.jpg","basaltolivine.html"],
	      ["basaltolivineproportion","basaltppl.jpg","basaltproportion.html"],
	      ["basaltcpx","basaltcpxppl.jpg","basaltcpx.html"],
	      ["basaltcpxproportion","basaltppl.jpg","basaltproportion.html"],
	      ["basaltorth","basaltorthppl.jpg","basaltorth.html"],
	      ["basaltorthproportion","basaltppl.jpg","basaltproportion.html"],
	      ["basaltplag","basaltplagppl.jpg","basaltplag.html"],
	      ["basaltplagproportion","basaltppl.jpg","basaltproportion.html"],
	      ["basaltmatrix","basaltmatrixppl.jpg","basaltmatrix.html"],
	      ["basaltmatrixzoom","basaltmatrixzoomppl.jpg","basaltmatrixzoom.html"],
	      ["basaltmatrixtexture","basaltmatrixtexture.jpg","basaltmatrixtexture.html"],
	      ["basaltpetrogenesis","basaltppl.jpg","basaltpetrogenesis.html"],
	      ["basalthand","handbasalt.jpg","handbasalt.html"],
	      ["basalthandgrainsize","basalthandgrainsize.jpg","handbasaltgrainsize.html"],
	      ["basalthandminerals","basalthandgrainsize.jpg","handbasaltminerals.html"],
	      ["basalthandcpx","basalthandcpx.jpg","basalthandcpx.html"],
	      ["basalthandolivine","basalthandolivine.jpg","basalthandolivine.html"],
	      ["basalthandconclusion","handbasalt.jpg","handbasaltconclusion.html"],
	      ["gabbro","handgabbro.jpg","gabbro.html"],
	      ["gabbrothinsection","gabbroppl.jpg","gabbrothinsection.html"],
	      ["gabbrointro","gabbroppl.jpg","gabbrointro.html"],
	      ["gabbroplag","gabbroplagppl.jpg","gabbroplag.html"],
	      ["gabbrocpx","gabbrocpxppl.jpg","gabbrocpx.html"],
	      ["gabbroolivine","gabbroolivineppl.jpg","gabbroolivine.html"],
	      ["gabbrothinsectionname","gabbroppl.jpg","gabbrothinsectionname.html"],
	      ["gabbrohand","handgabbro.jpg","gabbrohand.html"],
	      ["gabbrohandcpx","gabbrohandcpx.jpg","gabbrohandcpx.html"],
	      ["gabbrohandplag","gabbrohandplag.jpg","gabbrohandplag.html"],
	      ["gabbrohandolivine","gabbrohandolivine.jpg","gabbrohandolivine.html"],
	      ["gabbrohandconclusion","handgabbro.jpg","gabbrohandconclusion.html"],
	      ["granodiorite","granodioriteppl.JPG","sphene.html"],
	      ["test1","granodioriteppl1.JPG","granodiorite.html"],
	      ["spheneppl","spheneppl.html","sphenemovie.html"],
	      ["granodioriteppl","granodioriteppl.html","granodioritemovie.html"],
	      ["sedimentary","handsandstone.jpg","sedimentary.html"],
	      ["sandstone","handsandstone.jpg","sst.html"],
	      ["sandstonethinsection","sstppl.JPG","sandstoneqtz.html"],
	      ["sandstonethinsection2","sstppl.JPG","sandstoneqtz2.html"],
	      ["sandstonethinsection2b","sstppl.JPG","sandstoneqtz2b.html"],
	      ["sandstonethinsection3","sst4minppl.jpg","sandstoneqtz3.html"],
	      ["sandstonepcqtz","sstqtzppl.JPG","sandstonepcqtz.html"],
	      ["sandstone2qtz","sstppl.JPG","sandstone.html"],
	      ["sandstone3min","sst3min.JPG","sst3min.html"],
	      ["sandstonemicrocline","sstmicroclineppl.JPG","sstmicrocline.html"],
	      ["sandstonecement","sstcementppl.html","sstcement.html"],
	      ["sandstonehaematite","haematiteppl.jpg","ssthaematite.html"],
	      ["sandstonedeposition","sstdeposition.html","blank.txt"],
	      ["sandstonehandspecimen","handsandstone.jpg","blank.txt"],
	      ["ssthandzoom","ssthandzoom.jpg","blank.txt"],
	      ["ssthandzoom2","ssthandzoom2.jpg","blank.txt"],
	      ["oolites","handoolite.jpg","oo.html"],
	      ["oothin","oo.html","blank.txt"],
	      ["oothinsection","ooppl1.jpg","ooppl1.html"],
	      ["oobivalve","oobippl.jpg","oobippl.html"],
	      ["oobrachiopod1","oobrachppl.jpg","oobrach.html"],
	      ["oobrachiopod2","oobrachppl2.jpg","oobrach2.html"],
	      ["ooechinoderm","ooechppl.jpg","ooech.html"],
	      ["oooolite","ooooppl.jpg","oooo.html"],
	      ["oooooolite","ooooooppl.jpg","oooooo.html"],
	      ["oobryozoan","oobryoppl.jpg","oobryo.html"],
	      ["oopeloid","oopelppl.jpg","oopel.html"],
	      ["oosparite","oosparppl.jpg","oospar.html"],
	      ["oocement","oosparppl2.jpg","oospar2.html"],
	      ["ooconclusion","ooconclusion.jpg","blank.txt"],
	      ["oohandspecimen","handoolite.jpg","blank.txt"],
	      ["oolitehand2","oohandzoom.jpg","blank.txt"],
	      ["oolitehand3","oohandzoomzoom.jpg","blank.txt"],
	      ["gastropods","handgastropods.jpg","gast.html"],
	      ["gastthin","gast.html","blank.txt"],
	      ["gastthinsection","gastppl.jpg","gastthin.html"],
	      ["gast2","gastppl2.jpg","gastthin2.html"],
	      ["gast3","gastppl3.jpg","gastthin3.html"],
	      ["gast4","gastppl4.jpg","gastthin4.html"],
	      ["gast5","gastppl5.jpg","gastthin5.html"],
	      ["gast6","gastppl6.jpg","gastthin6.html"],
	      ["gastoverview","gastropodoverview.jpg","gastoverview.html"],
	      ["gasthandspecimen","handgastropods.jpg","handgastropod.html"],
	      ["gasthand2","gasthandzoom.jpg","handgastropod2.html"],
	      ["gasthand3","gasthandzoom2.jpg","blank.txt"],
	      ["gasthand4","gasthandzoom2zoom.jpg","handgastropod4.html"],
	      ["metamorphic","handschist.jpg","metamorphic.html"],
	      ["metamorphicinst","metamorphic.html","blank.html"],
	      ["schist","handschist.jpg","schist.html"],
	      ["schistthin","schistppl.jpg","schistthin.html"],
	      ["schistminerals","schistmineralsppl.jpg","schistminerals.html"],
	      ["schistmin","schistmineralsppl.jpg","schistminppl.html"],
	      ["schistbiotite","schistbiotiteppl.jpg","schistbiotite.html"],
	      ["schistsill","schistsillppl.jpg","schistsill.html"],
	      ["schistfibsill","schistfibsillppl.html","schistfibsill.html"],
	      ["schistgt","schistgtppl.jpg","schistgt.html"],
	      ["schistqtz","schistqtzppl.jpg","schistqtz.html"],
	      ["schistplag","schistplagppl.html","schistplag.html"],
	      ["schistosity","schistosityppl.jpg","schistosity.html"],
	      ["schistosity2","schistosityppl2.jpg","schistosity2.html"],
	      ["schistminident","schistminident.html","blank.txt"],
	      ["schistfabrics","schistosityppl.jpg","schistfabrics.html"],
	      ["schisttriplejunctions","schisttriplejunctions.jpg","schisttriplejunctions.html"],
	      ["schistgtxpl","schistgtxpl2.jpg","schistgtxpl.html"],
	      ["schistmodal","schistmodal.html","blank.txt"],
	      ["schistpetrogenesis","schistpetrogenesis.html","blank.txt"],
	      ["schisthand","handschist.jpg","handschist.html"],
	      ["schisthandzoom","schisthandzoom.jpg","schisthandzoom.html"],
	      ["schisthandzoomzoom","schisthandzoomzoom.jpg","schisthandzoomzoom.html"],
	      ["slate","handslate.jpg","slate.html"],
	      ["slatethin","slateandppl.jpg","slateand.html"],
	      ["slateand2","slateandppl2.jpg","slateand2.html"],
	      ["slateand3","slateandppl3.jpg","slateand3.html"],
	      ["slatecord","slatecordppl.jpg","slatecord.html"],
	      ["slatecord2","slatecordppl2.jpg","slatecord2.html"],
	      ["slatecordsectorzoning","slatecordsectorzoning1.jpg","slatecordsectorzoning.html"],
	      ["slatecord3","slatecordxpl3.jpg","blank.txt"],
	      ["slatecord4","slatecordxpl4.jpg","slatecord4.html"],
	      ["slatetexture","slatetextureppl.jpg","slatetexture.html"],
	      ["slatehand","handslate.jpg","slatehand.html"],
	      ["slatehand2","slatehand2.jpg","blank.txt"],
	      ["slatehand3","slatehand3.jpg","blank.txt"],
	      ["phyllite","handphyllite.jpg","phyllite.html"],
	      ["phyllitethin","phylliteppl.jpg","phyllite1.html"],
	      ["phyllite2","phylliteppl2.jpg","phyllite2.html"],
	      ["phylliteactinolite","phylliteactinoliteppl.jpg","phylliteactinolite.html"],
	      ["phyllitegarnet","phyllitegarnetppl.jpg","phyllitegt.html"],
	      ["phyllitegarnet2","phyllitegarnetppl2.jpg","phyllitegt2.html"],
	      ["phyllitebanding","phyllitebandingppl.jpg","phyllitebanding.html"],
	      ["phyllitebanding2","phyllitebandingppl2.jpg","phyllitebanding2.html"],
	      ["phyllitehand","handphyllite.jpg","blank.txt"],
	      ["phyllitehand2","phyllitehand2.jpg","blank.txt"]
];

function Next() {
	if (i<fnames.length-1){
		i++;
		loadPage();
	}
}

function Previous() {
	if (i>0){
		i--;
		loadPage();
	}
}

// doesn't update counter
function setPage(imagename,textname){
	document.getElementById('image').innerHTML =  
		"<object class=\"first\" data=\"intro/images/" + imagename + "\" type=\"text/html\">";
	document.getElementById('text').innerHTML =  
		"<object class=\"second\" data=\"intro/text/" + textname + "\" type=\"text/html\">";
}

// doesn't update counter
function setImage(imagename){
	document.getElementById('image').innerHTML =  
		"<object class=\"first\" data=\"intro/images/" + imagename + "\" type=\"text/html\">";
}

// updates counter
function loadPage(){
	document.getElementById('image').innerHTML =  
		"<object class=\"first\" data=\"intro/images/" + fnames[i][1] + "\" type=\"text/html\">";
	document.getElementById('text').innerHTML =  
		"<object class=\"second\" data=\"intro/text/" + fnames[i][2] + "\" type=\"text/html\">";
}

function getPage(name){
	for (var j=0; j<fnames.length; j++){
		if (fnames[j][0]==name) {
			i=j;
			loadPage();
			return;
		}
	}
}